[test]
preload = ["./test/setup.ts"]
coverage = true
coverageReporter = ["text", "lcov", "html"]
coverageDirectory = "./coverage"
coverageThreshold = { lines = 80, functions = 80, branches = 75, statements = 80 }